name: Test, build and publish package.

on:
  release:
    types: [published]

permissions:
  contents: read

jobs:
  prepare-machine:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'
    
  install-dependencies:
    runs-on: ubuntu-22.04

    steps:
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build pytest
        pip install -r requirement.txt

  testing:
    runs-on: ubuntu-22.04

    steps:
    - name: Run tests
      run: python -m pytest ./daily_tasks/tests/

  build-and-publish-package:
    runs-on: ubuntu-22.04

    steps:
    - name: Build package
      run: python -m build --sdist --wheel

    - name: Publish package
      uses: pypa/gh-action-pypi-publish@81e9d935c883d0b210363ab89cf05f3894778450
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository-url: https://test.pypi.org/legacy/